https://yts.mx/api/v2/list_movies.json

###
github.com/r-spacex/SpaceX-API

###
rapidapi.com/fyhao/api/currency-exchange

###
responsivevoice.org/api

###
https://api.cryptonator.com/api/full/btc-usd


###
openweathermap.org/api

###
https://www.tvmaze.com/api#full-schedule

###
icanhazdadjoke.com/api 

###
curl -H "Accept: application/json" https://icanhazdadjoke.com/

###
https://api.tvmaze.com/search/shows?q=girls

###
https://api.tvmaze.com/lookup/shows?imdb=tt8709752

###
https://api.tvmaze.com/shows/1/episodebynumber?season=1&number=1